name: CI

on:
  # Trigger on all pushes and pull requests
  push:
  pull_request:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Update repository
        run: |
          git submodule update --init --recursive
          git fetch --all
          git reset --hard origin/$(git branch --show-current)
          git submodule update --recursive --remote
      - name: Compile
        run: make all
      - name: Archive
        uses: actions/upload-artifact@v2
        with:
          name: PongoOS
          path: |
            build/checkra1n-kpf-pongo
            build/Pongo
            build/Pongo.bin
